attach(ROUT.SWETA)
hist(X1)
hist(X2)
hist(X3)
hist(X4)
hist(X5)
print("MEAN")
print(mean(X1))
print(mean(X2))
print(mean(X5))
print("VARIANCE")
print(var(X1))
print(var(X2))
print(var(X3))
print(var(X4))
print(mean(X3))
print(mean(X4))
print(var(X5))
res<-cor(ROUT.SWETA)
round(res,2)
boxplot(X1,main = "X1")
boxplot(X2,main = "X2")
boxplot(X3,main = "X3")
boxplot(X4,main = "X4")
boxplot(X5,main = "X5")

