attach(ROUT.SWETA)
plot(Y~X1, data = ROUT.SWETA)
Linear_Regression_X1<-lm(Y~X1,data = ROUT.SWETA)
summary(Linear_Regression_X1)
abline(Linear_Regression_X1)
hist(residuals(Linear_Regression_X1))
plot(Linear_Regression_X1)
chisq.test(abs(Y),abs(X1))
X1_Sq<-X1^2
Poynomial_Regression_X1<-lm(Y ~ X1 + (X1_Sq))
summary(Poynomial_Regression_X1)

plot(Y~X2, data = ROUT.SWETA)
Linear_Regression_X2<-lm(Y~X2,data = ROUT.SWETA)
summary(Linear_Regression_X2)
abline(Linear_Regression_X2)
hist(residuals(Linear_Regression_X2))
plot(Linear_Regression_X2)
chisq.test(abs(Y),abs(X2))
X2_Sq<-X2^2
Poynomial_Regression_X2<-lm(Y ~ X2 + (X2_Sq))
summary(Poynomial_Regression_X2)

plot(Y~X3, data = ROUT.SWETA)
Linear_Regression_X3<-lm(Y~X3,data = ROUT.SWETA)
summary(Linear_Regression_X3)
abline(Linear_Regression_X3)
hist(residuals(Linear_Regression_X3))
plot(Linear_Regression_X3)
chisq.test(abs(Y),abs(X3))
X3_Sq<-X3^2
Poynomial_Regression_X3<-lm(Y ~ X3 + (X3_Sq))
summary(Poynomial_Regression_X3)

plot(Y~X4, data = ROUT.SWETA)
Linear_Regression_X4<-lm(Y~X4,data = ROUT.SWETA)
summary(Linear_Regression_X4)
abline(Linear_Regression_X4)
hist(residuals(Linear_Regression_X4))
plot(Linear_Regression_X4)
chisq.test(abs(Y),abs(X4))
X4_Sq<-X4^2
Poynomial_Regression_X4<-lm(Y ~ X4 + (X4_Sq))
summary(Poynomial_Regression_X4)

plot(Y~X5, data = ROUT.SWETA)
Linear_Regression_X5<-lm(Y~X5,data = ROUT.SWETA)
summary(Linear_Regression_X5)
abline(Linear_Regression_X5)
hist(residuals(Linear_Regression_X5))
plot(Linear_Regression_X5)
chisq.test(abs(Y),abs(X5))
X5_Sq<-X5^2
Poynomial_Regression_X5<-lm(Y ~ X5 + (X5_Sq))
summary(Poynomial_Regression_X5)
